# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
