# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_auto_20161113_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hack',
            name='picture',
            field=models.ImageField(upload_to='../main/images/'),
        ),
    ]
