# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_wisdom_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisdom',
            name='rates',
        ),
        migrations.RemoveField(
            model_name='wisdom',
            name='rating',
        ),
    ]
