# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_auto_20161112_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisdom',
            name='end',
        ),
        migrations.RemoveField(
            model_name='wisdom',
            name='start',
        ),
        migrations.AddField(
            model_name='tip',
            name='end',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='start',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
