# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0004_auto_20161112_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='end',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='start',
        ),
    ]
