# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0005_auto_20161112_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
