# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0007_auto_20161112_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 0, 0)),
            preserve_default=False,
        ),
    ]
